[package]
edition = "2024"
name = "cross-agent"
version = "0.1.0"

[dependencies]
anyhow = "1.0.98"
async-fn-stream = "0.2.2"
axum = { version = "0.8.1", features = ["ws"] }
bytes = "1.10.1"
clap = { version = "4.5.37", features = ["derive"] }
fauxgen = "0.1.5"
futures = "0.3.31"
globset = "0.4.16"
humanize-bytes = "1.0.6"
indexmap = "2.9.0"
log = "0.4.27"
lz4_flex = "0.11.3"
nom = "8.0.0"
normpath = "1.3.0"
rkyv = "0.8.10"
simplelog = "0.12.2"
sysinfo = "0.35.1"
tokio = { version = "1.44.2", features = ["full"] }
walkdir = "2.5.0"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.61.1", features = ["Win32_Storage_FileSystem"] }

[profile.release]
lto = "fat"
panic = "abort"
strip = "symbols"
