[package]
edition = "2024"
name = "android-test"
version = "0.1.0"

[dependencies]
anyhow = "1.0.97"
async-fn-stream = "0.2.2"
axum = { version = "0.8.1", features = ["ws"] }
bytes = "1.10.1"
clap = { version = "4.5.32", features = ["derive"] }
humanize-bytes = "1.0.6"
lz4_flex = "0.11.3"
normpath = "1.3.0"
sysinfo = "0.33.1"
tokio = { version = "1.44.1", features = ["full"] }
walkdir = "2.5.0"

[profile.release]
lto = "fat"
panic = "abort"
strip = "symbols"
